import fs from 'fs'
import path from 'path'
import { getAllPosts, getPostBySlug as getMdxPost } from './mdx'
import { BlogPost } from '../types'
import { INDEXED_LOCALES } from '@/i18n/seo-locales'

// Load covers.json mapping (generated by scripts/fetch-covers.mjs)
type CoverMapping = Record<string, {
    path: string
    credit: string
    creditUrl: string
    source: 'unsplash' | 'pexels'
    sourceUrl: string
}>

let coverMapping: CoverMapping | null = null

function getCoverMapping(): CoverMapping {
    if (coverMapping) return coverMapping

    const mappingPath = path.join(process.cwd(), 'content', 'blog', 'covers.json')
    try {
        if (fs.existsSync(mappingPath)) {
            coverMapping = JSON.parse(fs.readFileSync(mappingPath, 'utf8'))
            return coverMapping!
        }
    } catch {
        // Silently fall back
    }

    coverMapping = {}
    return coverMapping
}

const ensureDefaults = (post: Partial<BlogPost>) => {
    if (!post.tags || !Array.isArray(post.tags)) post.tags = []
    // Frontmatter `author` is historically a plain string ("Andrew Altair" or
    // "Andrew Altair / Founder") while consumers read author.name / author.role -
    // without normalization Article JSON-LD shipped an empty Person on every post.
    const rawAuthor = post.author as unknown
    if (typeof rawAuthor === 'string') {
        const [name, role] = rawAuthor.split(/\s*\/\s*/)
        post.author = { name: name?.trim() || 'Andrew Altair', role: role?.trim() || 'Founder' }
    } else if (!rawAuthor || typeof (rawAuthor as { name?: unknown }).name !== 'string') {
        post.author = { name: 'Andrew Altair', role: 'Founder' }
    }
    return post
}

const ensureCoverImage = (post: Partial<BlogPost>) => {
    if (!post.coverImage && post.slug) {
        const mapping = getCoverMapping()
        const entry = mapping[post.slug]

        if (entry?.path) {
            post.coverImage = entry.path
            post.coverCredit = {
                credit: entry.credit,
                creditUrl: entry.creditUrl,
                source: entry.source,
                sourceUrl: entry.sourceUrl,
            }
            return post
        }
    }

    if (!post.coverImage) {
        // No fetched photo (e.g. Unsplash unavailable): generate a branded OG cover
        // from the post itself. BlogCard/BlogPost render `/api/og` covers with
        // `unoptimized`, and generateMetadata promotes it to an absolute og:image URL,
        // so the same card serves both the on-page cover and the social preview.
        const params = new URLSearchParams({ title: post.title || 'aiNOW' })
        const tags = post.tags?.filter(Boolean).slice(0, 3)
        if (tags && tags.length) params.set('tags', tags.join(','))
        post.coverImage = `/api/og?${params.toString()}`
    }

    // Attach credit even if coverImage was set in frontmatter
    if (!post.coverCredit && post.slug) {
        const mapping = getCoverMapping()
        const entry = mapping[post.slug]
        if (entry) {
            post.coverCredit = {
                credit: entry.credit,
                creditUrl: entry.creditUrl,
                source: entry.source,
                sourceUrl: entry.sourceUrl,
            }
        }
    }

    return post
}

export async function getPosts(locale: string = 'ka'): Promise<BlogPost[]> {
    const posts = getAllPosts(locale, [
        'id',
        'title',
        'date',
        'slug',
        'author',
        'coverImage',
        'excerpt',
        'tags',
    ])
    return posts.map(p => ensureDefaults(ensureCoverImage(p))) as BlogPost[]
}

export async function getPostBySlug(slug: string, locale: string = 'ka'): Promise<BlogPost | undefined> {
    const post = getMdxPost(slug, locale, [
        'title',
        'date',
        'slug',
        'author',
        'content',
        'coverImage',
        'excerpt',
        'tags',
        'readTime'
    ])

    if (!post.slug) return undefined
    return ensureDefaults(ensureCoverImage(post)) as BlogPost
}

export async function getRelatedPosts(currentSlug: string, locale: string = 'ka', limit: number = 3): Promise<BlogPost[]> {
    const allPosts = await getPosts(locale)
    const current = allPosts.find((p) => p.slug === currentSlug)
    if (!current) return []

    return allPosts
        .filter((p) => p.slug !== currentSlug)
        .map((p) => ({
            post: p,
            score: (p.tags || []).filter((t) => (current.tags || []).includes(t)).length,
        }))
        .sort((a, b) => b.score - a.score)
        .slice(0, limit)
        .map((p) => p.post)
}

// Only INDEXED_LOCALES are advertised in hreflang, even if a draft-locale .mdx happens to exist.
// A locale lights up here automatically once it is promoted in src/i18n/seo-locales.ts.
export function getAvailableLocales(slug: string): string[] {
    return INDEXED_LOCALES.filter(locale => {
        const filePath = path.join(process.cwd(), 'content/blog', locale, `${slug}.mdx`)
        return fs.existsSync(filePath)
    })
}

// Tag <-> URL slug helpers (shared with client components)
export { tagToSlug } from './slugify'
import { tagToSlug } from './slugify'

export async function getAllTags(locale: string = 'ka'): Promise<{ tag: string; slug: string; count: number }[]> {
    const posts = await getPosts(locale)
    const counts = new Map<string, number>()
    for (const p of posts) {
        for (const t of (p.tags || [])) {
            counts.set(t, (counts.get(t) ?? 0) + 1)
        }
    }
    return [...counts.entries()]
        .map(([tag, count]) => ({ tag, slug: tagToSlug(tag), count }))
        .sort((a, b) => b.count - a.count)
}

export async function getTagBySlug(slug: string, locale: string = 'ka'): Promise<{ tag: string; posts: BlogPost[] } | undefined> {
    const all = await getPosts(locale)
    // Find the tag name whose slug matches (first match wins)
    let matchedTag: string | undefined
    for (const p of all) {
        for (const t of (p.tags || [])) {
            if (tagToSlug(t) === slug) {
                matchedTag = t
                break
            }
        }
        if (matchedTag) break
    }
    if (!matchedTag) return undefined
    const posts = all.filter(p => (p.tags || []).some(t => tagToSlug(t) === slug))
    return { tag: matchedTag, posts }
}

export async function getAllTagSlugsAcrossLocales(): Promise<{ locale: string; slug: string }[]> {
    const locales = ['ka', 'en', 'ru']
    const out: { locale: string; slug: string }[] = []
    for (const locale of locales) {
        const tags = await getAllTags(locale)
        for (const { slug } of tags) {
            out.push({ locale, slug })
        }
    }
    return out
}

export async function getPostWithFallback(slug: string, locale: string): Promise<{ post: BlogPost; isFallback: boolean } | undefined> {
    const post = await getPostBySlug(slug, locale)
    if (post) return { post, isFallback: false }

    if (locale !== 'ka') {
        const fallback = await getPostBySlug(slug, 'ka')
        if (fallback) return { post: fallback, isFallback: true }
    }

    return undefined
}
