// Generates src/features/blog/lib/georgian-font.ts — the embedded font for next/og.
//
// WHY THIS EXISTS: the old georgian-font.ts held the base64 of a GitHub 404 HTML
// page (someone downloaded github.com/.../NotoSansGeorgian-Bold.ttf which 404s —
// google/fonts only ships the variable font, no static -Bold.ttf). Satori read
// "<!DOCTYPE html" instead of a font signature → "Unsupported OpenType signature"
// → "failed to pipe response" on every OG route. This script reads a REAL font
// from node_modules and refuses to embed anything that isn't one.
//
// Satori supports ttf / otf / woff — NOT woff2. @fontsource ships both; we use .woff.
// Regenerate after changing fonts:  node scripts/build-og-font.mjs

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..'); // website/
// Resolve @fontsource wherever it lives (hoisted to repo-root node_modules, or local).
const require = createRequire(import.meta.url);
const fontDir = join(dirname(require.resolve('@fontsource/noto-sans-georgian/package.json')), 'files');
const outFile = join(root, 'src/features/blog/lib/georgian-font.ts');

// Both subsets at weight 700 — Georgian glyphs for titles, Latin for aiNOW.ge / React / etc.
const subsets = {
  georgianFontBase64: 'noto-sans-georgian-georgian-700-normal.woff',
  latinFontBase64: 'noto-sans-georgian-latin-700-normal.woff',
};

function assertRealFont(buf, file) {
  const sig = buf.subarray(0, 4).toString('latin1');
  const isTtf = buf.length >= 4 && buf.readUInt32BE(0) === 0x00010000;
  const ok = isTtf || sig === 'OTTO' || sig === 'true' || sig === 'ttcf' || sig === 'wOFF';
  if (sig === 'wOF2') throw new Error(`${file}: woff2 — Satori cannot parse it. Use the .woff variant.`);
  if (!ok) throw new Error(`${file}: not a font (first bytes ${JSON.stringify(sig)}). Refusing to embed — this is the exact HTML-instead-of-font bug.`);
}

const b64 = {};
for (const [name, file] of Object.entries(subsets)) {
  const buf = readFileSync(join(fontDir, file));
  assertRealFont(buf, file);
  b64[name] = buf.toString('base64');
}

const out = `// AUTO-GENERATED by scripts/build-og-font.mjs — do not hand-edit.
// Noto Sans Georgian 700 (Georgian + Latin subsets) embedded for next/og ImageResponse.
// Source: @fontsource/noto-sans-georgian WOFF (Satori supports ttf/otf/woff, NOT woff2).
// Regenerate: node scripts/build-og-font.mjs
export const georgianFontBase64 = '${b64.georgianFontBase64}';
export const latinFontBase64 = '${b64.latinFontBase64}';

type OgFont = { name: string; data: Buffer; weight: 700; style: 'normal' };

// Pass BOTH subsets to Satori — it does per-glyph fallback across the array,
// so Georgian titles AND Latin labels (aiNOW.ge, React, ...) both render.
export const ogFonts: OgFont[] = [
  { name: 'Noto Sans Georgian', data: Buffer.from(georgianFontBase64, 'base64'), weight: 700, style: 'normal' },
  { name: 'Noto Sans Georgian', data: Buffer.from(latinFontBase64, 'base64'), weight: 700, style: 'normal' },
];
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, out);
console.log(`georgian-font.ts written — georgian ${b64.georgianFontBase64.length} + latin ${b64.latinFontBase64.length} base64 chars`);
